/*----------------------------------------------------------------------------------*/
/* Product:            Visual Data Mining and Machine Learning                      */
/* Release Version:    V2020.1.2                                                    */
/* Component Version:  V2020.1.1                                                    */
/* CAS Version:        V.04.00M0P01122021                                           */
/* SAS Version:        V.04.00M0P011221                                             */
/* Site Number:        70180938                                                     */
/* Host:               controller.sas-cas-server-default.purple.svc.cluster.local   */
/* Encoding:           utf-8                                                        */
/* Java Encoding:      UTF8                                                         */
/* Locale:             en_US                                                        */
/* Project GUID:       ae96cd5e-746e-4851-820d-f71972ed8010                         */
/* Node GUID:          65433aac-d152-418e-ba50-6e0bbd523ccd                         */
/* Node Id:            5ZTIC75GFH352E5HI9SI9MJF1                                    */
/* Algorithm:          Linear Regression                                            */
/* Generated by:       edmdev                                                       */
/* Date:               13JAN2021:23:28:48                                           */
/*----------------------------------------------------------------------------------*/
*------------------------------------------------------------*;
*Nodeid: _5ZTIC75GFH352E5HI9SI9MJF1;
*------------------------------------------------------------*;
   /*---------------------------------------------------------
     Generated SAS Scoring Code
     Date: 13Jan2021:23:28:47
     -------------------------------------------------------*/

   drop _badval_ _linp_ _temp_ _i_ _j_;
   _badval_ = 0;
   _linp_   = 0;
   _temp_   = 0;
   _i_      = 0;
   _j_      = 0;

   array _xrow_47092167_0_{47} _temporary_;
   array _beta_47092167_0_{47} _temporary_ (    35.2938690621398
          -0.00316801632733
           0.07786686829728
           0.00007312982284
            0.0000387204672
          -0.00001429869263
           0.01776027953126
          -3.89177968290856
                          0
           2.41423289467985
           1.01147060535678
           2.48618041566518
            2.8789877384842
           -1.9502737610076
           4.98274398591374
           19.0130843547702
                          0
                          0
          -0.21675095335064
          -0.48308473446692
          -1.89098467823302
          -4.09118704153411
                          0
                          0
                          0
                          0
          -0.46812012859749
           -0.8636133621023
          -0.37711853118967
          -2.98976757778881
           1.69578552895761
                          0
          -3.52978125478295
          -1.52235961621419
            -1.036890003916
           0.04102415679592
           0.69940087729199
           3.18330571963071
          -1.34122633761735
           1.55964927244529
          -16.6516421879405
          -0.93939190305239
           1.30149942144832
                          0
                          0
          -1.17472895287215
                          0);

   length _JOB_ $7; drop _JOB_;
   _JOB_ = left(trim(put(JOB,$7.)));
   length _NINQ_ $2; drop _NINQ_;
   _NINQ_ = left(trim(put(NINQ,BEST2.)));
   length _DEROG_ $2; drop _DEROG_;
   _DEROG_ = left(trim(put(DEROG,BEST2.)));
   length _BAD_ $1; drop _BAD_;
   _BAD_ = left(trim(put(BAD,BEST1.)));
   length _DELINQ_ $2; drop _DELINQ_;
   _DELINQ_ = left(trim(put(DELINQ,BEST2.)));
   length _REASON_ $7; drop _REASON_;
   _REASON_ = left(trim(put(REASON,$7.)));
   if missing(CLNO)
      or missing(MORTDUE)
      or missing(VALUE)
      or missing(LOAN)
      or missing(YOJ)
      or missing(CLAGE)
      then do;
         _badval_ = 1;
         goto skip_47092167_0;
   end;

   do _i_=1 to 47; _xrow_47092167_0_{_i_} = 0; end;

   _xrow_47092167_0_[1] = 1;

   _xrow_47092167_0_[2] = CLAGE;

   _xrow_47092167_0_[3] = CLNO;

   _xrow_47092167_0_[4] = LOAN;

   _xrow_47092167_0_[5] = MORTDUE;

   _xrow_47092167_0_[6] = VALUE;

   _xrow_47092167_0_[7] = YOJ;

   _temp_ = 1;
   select (_BAD_);
      when ('0') _xrow_47092167_0_[8] = _temp_;
      when ('1') _xrow_47092167_0_[9] = _temp_;
      otherwise do; _badval_ = 1; goto skip_47092167_0; end;
   end;

   _temp_ = 1;
   select (_DELINQ_);
      when ('0') _xrow_47092167_0_[10] = _temp_;
      when ('1') _xrow_47092167_0_[11] = _temp_;
      when ('2') _xrow_47092167_0_[12] = _temp_;
      when ('3') _xrow_47092167_0_[13] = _temp_;
      when ('4') _xrow_47092167_0_[14] = _temp_;
      when ('5') _xrow_47092167_0_[15] = _temp_;
      when ('6') _xrow_47092167_0_[16] = _temp_;
      when ('7') _xrow_47092167_0_[17] = _temp_;
      when ('10') _xrow_47092167_0_[18] = _temp_;
      otherwise do; _badval_ = 1; goto skip_47092167_0; end;
   end;

   _temp_ = 1;
   select (_DEROG_);
      when ('0') _xrow_47092167_0_[19] = _temp_;
      when ('1') _xrow_47092167_0_[20] = _temp_;
      when ('2') _xrow_47092167_0_[21] = _temp_;
      when ('3') _xrow_47092167_0_[22] = _temp_;
      when ('4') _xrow_47092167_0_[23] = _temp_;
      when ('5') _xrow_47092167_0_[24] = _temp_;
      when ('7') _xrow_47092167_0_[25] = _temp_;
      when ('10') _xrow_47092167_0_[26] = _temp_;
      otherwise do; _badval_ = 1; goto skip_47092167_0; end;
   end;

   _temp_ = 1;
   select (_JOB_);
      when ('Mgr') _xrow_47092167_0_[27] = _temp_;
      when ('Office') _xrow_47092167_0_[28] = _temp_;
      when ('Other') _xrow_47092167_0_[29] = _temp_;
      when ('ProfExe') _xrow_47092167_0_[30] = _temp_;
      when ('Sales') _xrow_47092167_0_[31] = _temp_;
      when ('Self') _xrow_47092167_0_[32] = _temp_;
      otherwise do; _badval_ = 1; goto skip_47092167_0; end;
   end;

   _temp_ = 1;
   select (_NINQ_);
      when ('0') _xrow_47092167_0_[33] = _temp_;
      when ('1') _xrow_47092167_0_[34] = _temp_;
      when ('2') _xrow_47092167_0_[35] = _temp_;
      when ('3') _xrow_47092167_0_[36] = _temp_;
      when ('4') _xrow_47092167_0_[37] = _temp_;
      when ('5') _xrow_47092167_0_[38] = _temp_;
      when ('6') _xrow_47092167_0_[39] = _temp_;
      when ('7') _xrow_47092167_0_[40] = _temp_;
      when ('8') _xrow_47092167_0_[41] = _temp_;
      when ('9') _xrow_47092167_0_[42] = _temp_;
      when ('10') _xrow_47092167_0_[43] = _temp_;
      when ('11') _xrow_47092167_0_[44] = _temp_;
      when ('13') _xrow_47092167_0_[45] = _temp_;
      otherwise do; _badval_ = 1; goto skip_47092167_0; end;
   end;

   _temp_ = 1;
   select (_REASON_);
      when ('DebtCon') _xrow_47092167_0_[46] = _temp_;
      when ('HomeImp') _xrow_47092167_0_[47] = _temp_;
      otherwise do; _badval_ = 1; goto skip_47092167_0; end;
   end;

   do _i_=1 to 47;
      _linp_ + _xrow_47092167_0_{_i_} * _beta_47092167_0_{_i_};
   end;

   skip_47092167_0:
   label P_DEBTINC = 'Predicted: DEBTINC';
   if (_badval_ eq 0) and not missing(_linp_) then do;
      P_DEBTINC = _linp_;
   end; else do;
      _linp_ = .;
      P_DEBTINC = .;
   end;


   *------------------------------------------------------------*;
   * Accounting for missing predicted variable;
   *------------------------------------------------------------*;
   label "P_DEBTINC"n ='Predicted: DEBTINC';
   if "P_DEBTINC"n = . then "P_DEBTINC"n =33.473329522;
*------------------------------------------------------------*;
* Generating fixed output names;
*------------------------------------------------------------*;
Length EM_PREDICTION 8;
LABEL EM_PREDICTION= "Prediction for DEBTINC";
EM_PREDICTION= 'P_DEBTINC'n;
