apiVersion: v1
kind: Service
metadata:
  annotations:
    sas.com/component-name: sas-scr-PLACEHOLDER
    sas.com/tls-enabled-ports: all
  labels:
    sas.com/deployment: sas-scr-PLACEHOLDER
  name: sas-scr-PLACEHOLDER
  namespace: default
spec:
  ports:
  - name: apiserver
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app: sas-scr-PLACEHOLDER
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}